import { User, Category, Product, Supplier, PurchaseOrder, Sale, StockAdjustment, ProductReturn } from '@/types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin',
    name: 'Md. Yeasin Arafat',
    email: 'admin@ims.nstu.edu.bd',
    role: 'Administrator',
    status: 'Active',
    phone: '+880 1812-345678',
    createdAt: '2026-01-10T08:00:00Z',
    lastLogin: '2026-08-31T08:30:00Z',
  },
  {
    id: 'usr_inventory',
    name: 'Ahosan Habib',
    email: 'inventory@ims.nstu.edu.bd',
    role: 'Inventory Manager',
    status: 'Active',
    phone: '+880 1711-223344',
    createdAt: '2026-01-15T09:00:00Z',
    lastLogin: '2026-08-30T16:20:00Z',
  },
  {
    id: 'usr_purchase',
    name: 'Dr. Nazia Majadi',
    email: 'purchase@ims.nstu.edu.bd',
    role: 'Purchase Manager',
    status: 'Active',
    phone: '+880 1912-998877',
    createdAt: '2026-01-20T10:00:00Z',
    lastLogin: '2026-08-31T07:45:00Z',
  },
  {
    id: 'usr_cashier',
    name: 'Tanvir Hossain',
    email: 'cashier@ims.nstu.edu.bd',
    role: 'Cashier',
    status: 'Active',
    phone: '+880 1622-445566',
    createdAt: '2026-02-01T11:00:00Z',
    lastLogin: '2026-08-31T09:00:00Z',
  },
  {
    id: 'usr_pending_1',
    name: 'Shakil Ahmed',
    email: 'shakil.cste@gmail.com',
    role: 'Cashier',
    requestedRole: 'Cashier',
    status: 'Pending Approval',
    phone: '+880 1521-778899',
    createdAt: '2026-08-29T14:20:00Z',
  },
  {
    id: 'usr_pending_2',
    name: 'Nusrat Jahan',
    email: 'nusrat.ims@outlook.com',
    role: 'Inventory Manager',
    requestedRole: 'Inventory Manager',
    status: 'Pending Approval',
    phone: '+880 1301-445588',
    createdAt: '2026-08-30T18:10:00Z',
  }
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_beverages', name: 'Beverages & Drinks', description: 'Juices, soda, tea, coffee, and mineral water', icon: 'Coffee', productCount: 4 },
  { id: 'cat_groceries', name: 'Food & Groceries', description: 'Rice, oil, spices, snacks, noodles', icon: 'ShoppingBag', productCount: 5 },
  { id: 'cat_dairy', name: 'Dairy & Bakery', description: 'Milk, cheese, butter, bread, biscuits', icon: 'Milk', productCount: 4 },
  { id: 'cat_personal_care', name: 'Personal Care & Hygiene', description: 'Soaps, shampoos, toothpaste, skin care', icon: 'Sparkles', productCount: 4 },
  { id: 'cat_electronics', name: 'Electronics & Accessories', description: 'Cables, chargers, batteries, flash drives', icon: 'Smartphone', productCount: 3 },
  { id: 'cat_stationery', name: 'Office & Stationery', description: 'Notebooks, pens, staplers, paper reams', icon: 'BookOpen', productCount: 3 },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_pran',
    name: 'PRAN-RFL Group Ltd.',
    contactPerson: 'Kamrul Hasan',
    phone: '+880 1713-112233',
    email: 'supply@pranfoods.net',
    address: 'PRAN-RFL Center, Middle Badda, Dhaka 1212',
    paymentTerms: 'Net 30',
    status: 'Active',
    totalPurchased: 450000,
    totalPaid: 380000,
    totalDue: 70000,
    createdAt: '2026-01-05T00:00:00Z',
    suppliedProducts: [
      { productId: 'prod_pran_mango', productName: 'PRAN Frooto Mango Juice 250ml', sku: 'PRAN-FRT-250', supplierPrice: 28, minOrderQuantity: 24 },
      { productId: 'prod_pran_spice', productName: 'PRAN Turmeric Powder 200g', sku: 'PRAN-TUR-200', supplierPrice: 55, minOrderQuantity: 12 },
      { productId: 'prod_pran_sauce', productName: 'PRAN Tomato Sauce 340g', sku: 'PRAN-SAU-340', supplierPrice: 72, minOrderQuantity: 12 },
      { productId: 'prod_pran_potata', productName: 'PRAN Potata Spicy Biscuits 100g', sku: 'PRAN-POT-100', supplierPrice: 20, minOrderQuantity: 30 },
    ]
  },
  {
    id: 'sup_square',
    name: 'Square Consumer Products Ltd.',
    contactPerson: 'Mehedi Hasan',
    phone: '+880 1819-887766',
    email: 'order@squaregroup.com',
    address: 'Square Centre, 48 Mohakhali C/A, Dhaka 1212',
    paymentTerms: 'Net 15',
    status: 'Active',
    totalPurchased: 520000,
    totalPaid: 470000,
    totalDue: 50000,
    createdAt: '2026-01-08T00:00:00Z',
    suppliedProducts: [
      { productId: 'prod_radhuni_oil', productName: 'Radhuni Pure Mustard Oil 500ml', sku: 'RAD-MST-500', supplierPrice: 160, minOrderQuantity: 12 },
      { productId: 'prod_radhuni_biryani', productName: 'Radhuni Biryani Masala 40g', sku: 'RAD-BRY-40', supplierPrice: 42, minOrderQuantity: 24 },
      { productId: 'prod_meril_soap', productName: 'Meril Splash Beauty Soap 100g', sku: 'MRL-SPL-100', supplierPrice: 48, minOrderQuantity: 36 },
      { productId: 'prod_chashi_rice', productName: 'Chashi Chinigura Aromatic Rice 1kg', sku: 'CHS-RCE-1K', supplierPrice: 135, minOrderQuantity: 10 },
    ]
  },
  {
    id: 'sup_unilever',
    name: 'Unilever Bangladesh Limited',
    contactPerson: 'Farhana Akhter',
    phone: '+880 1711-990011',
    email: 'orders.bd@unilever.com',
    address: 'ZN Tower, Plot 2, Road 8, Gulshan 1, Dhaka 1212',
    paymentTerms: 'Net 30',
    status: 'Active',
    totalPurchased: 680000,
    totalPaid: 680000,
    totalDue: 0,
    createdAt: '2026-01-12T00:00:00Z',
    suppliedProducts: [
      { productId: 'prod_lux_soap', productName: 'Lux Soft Touch Soap 150g', sku: 'LUX-SFT-150', supplierPrice: 75, minOrderQuantity: 24 },
      { productId: 'prod_dove_shampoo', productName: 'Dove Intense Repair Shampoo 340ml', sku: 'DOV-SHP-340', supplierPrice: 380, minOrderQuantity: 12 },
      { productId: 'prod_close_up', productName: 'Close Up Deep Action Toothpaste 100g', sku: 'CLU-TP-100', supplierPrice: 85, minOrderQuantity: 24 },
      { productId: 'prod_surf_excel', productName: 'Surf Excel Quick Wash Detergent 500g', sku: 'SRF-EXC-500', supplierPrice: 110, minOrderQuantity: 16 },
    ]
  },
  {
    id: 'sup_nestle',
    name: 'Nestlé Bangladesh PLC',
    contactPerson: 'Sabbir Rahman',
    phone: '+880 1914-554433',
    email: 'direct.sales@bd.nestle.com',
    address: 'Gulshan-2, Dhaka 1212',
    paymentTerms: 'Cash On Delivery',
    status: 'Active',
    totalPurchased: 310000,
    totalPaid: 275000,
    totalDue: 35000,
    createdAt: '2026-01-18T00:00:00Z',
    suppliedProducts: [
      { productId: 'prod_maggi_noodles', productName: 'Maggi 2-Minute Masala Noodles (Pack of 8)', sku: 'MAG-NDL-PK8', supplierPrice: 145, minOrderQuantity: 10 },
      { productId: 'prod_nescafe_classic', productName: 'Nescafe Classic Instant Coffee Jar 50g', sku: 'NES-COF-50G', supplierPrice: 220, minOrderQuantity: 12 },
      { productId: 'prod_nido_milk', productName: 'Nido FortiGrow Full Cream Milk Powder 400g', sku: 'NID-MLK-400', supplierPrice: 430, minOrderQuantity: 8 },
    ]
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_pran_mango',
    name: 'PRAN Frooto Mango Juice 250ml',
    sku: 'PRAN-FRT-250',
    barcode: '894110000101',
    description: 'Refreshing real mango juice drink in ready to drink pet bottle',
    categoryId: 'cat_beverages',
    categoryName: 'Beverages & Drinks',
    brand: 'PRAN',
    purchasePrice: 28,
    sellingPrice: 35,
    discount: 0,
    stockQuantity: 142,
    minStockLevel: 25,
    unit: 'pcs',
    supplierId: 'sup_pran',
    supplierName: 'PRAN-RFL Group Ltd.',
    status: 'Active',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-08-30T10:00:00Z',
  },
  {
    id: 'prod_nescafe_classic',
    name: 'Nescafe Classic Instant Coffee Jar 50g',
    sku: 'NES-COF-50G',
    barcode: '894110000102',
    description: '100% pure roasted coffee granules with rich aroma',
    categoryId: 'cat_beverages',
    categoryName: 'Beverages & Drinks',
    brand: 'Nescafe',
    purchasePrice: 220,
    sellingPrice: 270,
    discount: 5,
    stockQuantity: 28,
    minStockLevel: 10,
    unit: 'pcs',
    supplierId: 'sup_nestle',
    supplierName: 'Nestlé Bangladesh PLC',
    status: 'Active',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-08-28T14:00:00Z',
  },
  {
    id: 'prod_radhuni_oil',
    name: 'Radhuni Pure Mustard Oil 500ml',
    sku: 'RAD-MST-500',
    barcode: '894110000103',
    description: 'Cold-pressed authentic pungent mustard oil for traditional cooking',
    categoryId: 'cat_groceries',
    categoryName: 'Food & Groceries',
    brand: 'Radhuni',
    purchasePrice: 160,
    sellingPrice: 190,
    discount: 0,
    stockQuantity: 45,
    minStockLevel: 15,
    unit: 'pcs',
    supplierId: 'sup_square',
    supplierName: 'Square Consumer Products Ltd.',
    status: 'Active',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
  {
    id: 'prod_chashi_rice',
    name: 'Chashi Chinigura Aromatic Rice 1kg',
    sku: 'CHS-RCE-1K',
    barcode: '894110000104',
    description: 'Premium aromatic Chinigura rice for biryani, polao, and desserts',
    categoryId: 'cat_groceries',
    categoryName: 'Food & Groceries',
    brand: 'Chashi',
    purchasePrice: 135,
    sellingPrice: 165,
    discount: 10,
    stockQuantity: 80,
    minStockLevel: 20,
    unit: 'kg',
    supplierId: 'sup_square',
    supplierName: 'Square Consumer Products Ltd.',
    status: 'Active',
    createdAt: '2026-01-12T00:00:00Z',
    updatedAt: '2026-08-29T16:00:00Z',
  },
  {
    id: 'prod_maggi_noodles',
    name: 'Maggi 2-Minute Masala Noodles (Pack of 8)',
    sku: 'MAG-NDL-PK8',
    barcode: '894110000105',
    description: 'Family value pack instant noodles with signature spice mix',
    categoryId: 'cat_groceries',
    categoryName: 'Food & Groceries',
    brand: 'Maggi',
    purchasePrice: 145,
    sellingPrice: 175,
    discount: 0,
    stockQuantity: 52,
    minStockLevel: 15,
    unit: 'box',
    supplierId: 'sup_nestle',
    supplierName: 'Nestlé Bangladesh PLC',
    status: 'Active',
    createdAt: '2026-01-18T00:00:00Z',
    updatedAt: '2026-08-30T12:00:00Z',
  },
  {
    id: 'prod_nido_milk',
    name: 'Nido FortiGrow Full Cream Milk Powder 400g',
    sku: 'NID-MLK-400',
    barcode: '894110000106',
    description: 'Fortified nutrition full cream milk powder for whole family',
    categoryId: 'cat_dairy',
    categoryName: 'Dairy & Bakery',
    brand: 'Nido',
    purchasePrice: 430,
    sellingPrice: 495,
    discount: 15,
    stockQuantity: 18,
    minStockLevel: 12,
    unit: 'pcs',
    supplierId: 'sup_nestle',
    supplierName: 'Nestlé Bangladesh PLC',
    status: 'Active',
    createdAt: '2026-01-22T00:00:00Z',
    updatedAt: '2026-08-31T07:00:00Z',
  },
  {
    id: 'prod_pran_potata',
    name: 'PRAN Potata Spicy Biscuits 100g',
    sku: 'PRAN-POT-100',
    barcode: '894110000107',
    description: 'Crispy potato-based seasoned crunchy spicy snacks biscuit',
    categoryId: 'cat_dairy',
    categoryName: 'Dairy & Bakery',
    brand: 'PRAN',
    purchasePrice: 20,
    sellingPrice: 25,
    discount: 0,
    stockQuantity: 8, // Low stock demo!
    minStockLevel: 20,
    unit: 'pcs',
    supplierId: 'sup_pran',
    supplierName: 'PRAN-RFL Group Ltd.',
    status: 'Active',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-31T08:00:00Z',
  },
  {
    id: 'prod_lux_soap',
    name: 'Lux Soft Touch Soap 150g',
    sku: 'LUX-SFT-150',
    barcode: '894110000108',
    description: 'Infused with floral beauty oil and french rose fragrance',
    categoryId: 'cat_personal_care',
    categoryName: 'Personal Care & Hygiene',
    brand: 'Lux',
    purchasePrice: 75,
    sellingPrice: 90,
    discount: 0,
    stockQuantity: 64,
    minStockLevel: 20,
    unit: 'pcs',
    supplierId: 'sup_unilever',
    supplierName: 'Unilever Bangladesh Limited',
    status: 'Active',
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-08-28T09:00:00Z',
  },
  {
    id: 'prod_dove_shampoo',
    name: 'Dove Intense Repair Shampoo 340ml',
    sku: 'DOV-SHP-340',
    barcode: '894110000109',
    description: 'Nutritive serum restores strength against breakage',
    categoryId: 'cat_personal_care',
    categoryName: 'Personal Care & Hygiene',
    brand: 'Dove',
    purchasePrice: 380,
    sellingPrice: 450,
    discount: 25,
    stockQuantity: 4, // Critical low stock!
    minStockLevel: 10,
    unit: 'bottle',
    supplierId: 'sup_unilever',
    supplierName: 'Unilever Bangladesh Limited',
    status: 'Active',
    createdAt: '2026-02-05T00:00:00Z',
    updatedAt: '2026-08-30T17:00:00Z',
  },
  {
    id: 'prod_close_up',
    name: 'Close Up Deep Action Toothpaste 100g',
    sku: 'CLU-TP-100',
    barcode: '894110000110',
    description: 'Red hot gel with active zinc mouthwash for fresh breath',
    categoryId: 'cat_personal_care',
    categoryName: 'Personal Care & Hygiene',
    brand: 'Close Up',
    purchasePrice: 85,
    sellingPrice: 105,
    discount: 0,
    stockQuantity: 92,
    minStockLevel: 15,
    unit: 'pcs',
    supplierId: 'sup_unilever',
    supplierName: 'Unilever Bangladesh Limited',
    status: 'Active',
    createdAt: '2026-01-28T00:00:00Z',
    updatedAt: '2026-08-29T10:00:00Z',
  }
];

export const INITIAL_PURCHASES: PurchaseOrder[] = [
  {
    id: 'po_1001',
    poNumber: 'PO-2026-001',
    supplierId: 'sup_pran',
    supplierName: 'PRAN-RFL Group Ltd.',
    supplierPhone: '+880 1713-112233',
    items: [
      { productId: 'prod_pran_mango', productName: 'PRAN Frooto Mango Juice 250ml', sku: 'PRAN-FRT-250', unitCost: 28, quantity: 100, subtotal: 2800 },
      { productId: 'prod_pran_potata', productName: 'PRAN Potata Spicy Biscuits 100g', sku: 'PRAN-POT-100', unitCost: 20, quantity: 60, subtotal: 1200 }
    ],
    totalAmount: 4000,
    paidAmount: 4000,
    dueAmount: 0,
    status: 'Received',
    paymentStatus: 'Paid',
    orderDate: '2026-08-20T10:30:00Z',
    receivedDate: '2026-08-22T14:15:00Z',
    createdBy: 'Dr. Nazia Majadi',
    notes: 'Standard replenishment batch for front retail racks.',
    paymentHistory: [
      {
        id: 'pay_rec_01',
        paymentDate: '2026-08-22T14:30:00Z',
        amountPaid: 4000,
        previousDue: 4000,
        remainingDue: 0,
        paymentMethod: 'Bank Transfer',
        transactionRef: 'EFT-8899120',
        receiptNumber: 'RCP-PRN-001',
        notes: 'Full payment via City Bank corporate transfer',
        recordedBy: 'Dr. Nazia Majadi'
      }
    ]
  },
  {
    id: 'po_1002',
    poNumber: 'PO-2026-002',
    supplierId: 'sup_square',
    supplierName: 'Square Consumer Products Ltd.',
    supplierPhone: '+880 1819-887766',
    items: [
      { productId: 'prod_radhuni_oil', productName: 'Radhuni Pure Mustard Oil 500ml', sku: 'RAD-MST-500', unitCost: 160, quantity: 50, subtotal: 8000 },
      { productId: 'prod_chashi_rice', productName: 'Chashi Chinigura Aromatic Rice 1kg', sku: 'CHS-RCE-1K', unitCost: 135, quantity: 80, subtotal: 10800 }
    ],
    totalAmount: 18800,
    paidAmount: 10000,
    dueAmount: 8800,
    status: 'Received',
    paymentStatus: 'Partial',
    orderDate: '2026-08-24T11:00:00Z',
    receivedDate: '2026-08-26T16:00:00Z',
    createdBy: 'Dr. Nazia Majadi',
    notes: 'Initial advance paid 10,000 BDT, remaining due on 30th.',
    paymentHistory: [
      {
        id: 'pay_rec_02',
        paymentDate: '2026-08-24T11:30:00Z',
        amountPaid: 10000,
        previousDue: 18800,
        remainingDue: 8800,
        paymentMethod: 'bKash',
        transactionRef: 'BK9X87261A',
        receiptNumber: 'RCP-SQR-001',
        notes: 'bKash merchant advance payment',
        recordedBy: 'Dr. Nazia Majadi'
      }
    ]
  },
  {
    id: 'po_1003',
    poNumber: 'PO-2026-003',
    supplierId: 'sup_unilever',
    supplierName: 'Unilever Bangladesh Limited',
    supplierPhone: '+880 1711-990011',
    items: [
      { productId: 'prod_lux_soap', productName: 'Lux Soft Touch Soap 150g', sku: 'LUX-SFT-150', unitCost: 75, quantity: 48, subtotal: 3600 },
      { productId: 'prod_dove_shampoo', productName: 'Dove Intense Repair Shampoo 340ml', sku: 'DOV-SHP-340', unitCost: 380, quantity: 24, subtotal: 9120 },
      { productId: 'prod_close_up', productName: 'Close Up Deep Action Toothpaste 100g', sku: 'CLU-TP-100', unitCost: 85, quantity: 48, subtotal: 4080 }
    ],
    totalAmount: 16800,
    paidAmount: 0,
    dueAmount: 16800,
    status: 'Requested',
    paymentStatus: 'Due',
    orderDate: '2026-08-30T09:15:00Z',
    createdBy: 'Dr. Nazia Majadi',
    notes: 'High priority restock order awaiting supplier dispatch.',
    paymentHistory: []
  }
];

export const INITIAL_SALES: Sale[] = [
  {
    id: 'sale_101',
    invoiceNumber: 'INV-2026-8801',
    cashierId: 'usr_cashier',
    cashierName: 'Tanvir Hossain',
    customerName: 'Ashraf Ali',
    customerPhone: '01819002233',
    items: [
      { productId: 'prod_pran_mango', productName: 'PRAN Frooto Mango Juice 250ml', barcode: '894110000101', sku: 'PRAN-FRT-250', unitPrice: 35, discount: 0, quantity: 3, subtotal: 105, costPrice: 28 },
      { productId: 'prod_chashi_rice', productName: 'Chashi Chinigura Aromatic Rice 1kg', barcode: '894110000104', sku: 'CHS-RCE-1K', unitPrice: 165, discount: 10, quantity: 2, subtotal: 310, costPrice: 135 }
    ],
    subtotal: 415,
    discountTotal: 20,
    taxRate: 5,
    taxAmount: 20.75,
    totalAmount: 435.75,
    paidAmount: 500,
    changeAmount: 64.25,
    paymentMethod: 'Cash',
    paymentDetails: {
      method: 'Cash',
      cashTendered: 500,
      changeGiven: 64.25
    },
    saleDate: '2026-08-31T08:15:00Z',
    status: 'Completed',
    notes: 'Regular retail purchase'
  },
  {
    id: 'sale_102',
    invoiceNumber: 'INV-2026-8802',
    cashierId: 'usr_cashier',
    cashierName: 'Tanvir Hossain',
    customerName: 'Samira Rahman',
    customerPhone: '01712998877',
    items: [
      { productId: 'prod_nescafe_classic', productName: 'Nescafe Classic Instant Coffee Jar 50g', barcode: '894110000102', sku: 'NES-COF-50G', unitPrice: 270, discount: 5, quantity: 1, subtotal: 265, costPrice: 220 },
      { productId: 'prod_nido_milk', productName: 'Nido FortiGrow Full Cream Milk Powder 400g', barcode: '894110000106', sku: 'NID-MLK-400', unitPrice: 495, discount: 15, quantity: 1, subtotal: 480, costPrice: 430 }
    ],
    subtotal: 745,
    discountTotal: 20,
    taxRate: 5,
    taxAmount: 37.25,
    totalAmount: 782.25,
    paidAmount: 782.25,
    changeAmount: 0,
    paymentMethod: 'bKash',
    paymentDetails: {
      method: 'bKash',
      mobileNumber: '01712998877',
      trxId: 'BK782928374A'
    },
    saleDate: '2026-08-31T08:45:00Z',
    status: 'Completed'
  },
  {
    id: 'sale_103',
    invoiceNumber: 'INV-2026-8803',
    cashierId: 'usr_cashier',
    cashierName: 'Tanvir Hossain',
    customerName: 'Kazi Faruk',
    customerPhone: '01911445566',
    items: [
      { productId: 'prod_radhuni_oil', productName: 'Radhuni Pure Mustard Oil 500ml', barcode: '894110000103', sku: 'RAD-MST-500', unitPrice: 190, discount: 0, quantity: 2, subtotal: 380, costPrice: 160 },
      { productId: 'prod_lux_soap', productName: 'Lux Soft Touch Soap 150g', barcode: '894110000108', sku: 'LUX-SFT-150', unitPrice: 90, discount: 0, quantity: 3, subtotal: 270, costPrice: 75 }
    ],
    subtotal: 650,
    discountTotal: 0,
    taxRate: 5,
    taxAmount: 32.50,
    totalAmount: 682.50,
    paidAmount: 682.50,
    changeAmount: 0,
    paymentMethod: 'Nagad',
    paymentDetails: {
      method: 'Nagad',
      mobileNumber: '01911445566',
      trxId: 'NG482019382B'
    },
    saleDate: '2026-08-31T09:05:00Z',
    status: 'Completed'
  }
];

export const INITIAL_ADJUSTMENTS: StockAdjustment[] = [
  {
    id: 'adj_01',
    productId: 'prod_pran_potata',
    productName: 'PRAN Potata Spicy Biscuits 100g',
    sku: 'PRAN-POT-100',
    adjustmentType: 'Stock Out',
    quantityBefore: 12,
    quantityChange: -4,
    quantityAfter: 8,
    reason: 'Damaged packaging during store restocking',
    date: '2026-08-29T11:00:00Z',
    adjustedBy: 'Ahosan Habib'
  },
  {
    id: 'adj_02',
    productId: 'prod_dove_shampoo',
    productName: 'Dove Intense Repair Shampoo 340ml',
    sku: 'DOV-SHP-340',
    adjustmentType: 'Correction',
    quantityBefore: 6,
    quantityChange: -2,
    quantityAfter: 4,
    reason: 'Physical shelf count audit correction',
    date: '2026-08-30T15:30:00Z',
    adjustedBy: 'Ahosan Habib'
  }
];

export const INITIAL_RETURNS: ProductReturn[] = [
  {
    id: 'ret_01',
    returnNumber: 'RET-2026-001',
    saleId: 'sale_101',
    invoiceNumber: 'INV-2026-8801',
    productId: 'prod_pran_mango',
    productName: 'PRAN Frooto Mango Juice 250ml',
    quantity: 1,
    unitPrice: 35,
    refundAmount: 35,
    reason: 'Customer mistakenly selected regular mango instead of apple juice',
    returnDate: '2026-08-31T08:30:00Z',
    processedBy: 'Tanvir Hossain',
    status: 'Approved'
  }
];
